package jdbc_test;

import com.mysql.jdbc.Connection;
import com.toedter.calendar.IDateEditor;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import java.awt.Image;
import java.io.FileNotFoundException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class AddNew extends javax.swing.JFrame {
   
   private ImageIcon format=null;
   String fname=null;
   int s=0;
   byte[] pimage=null;
   Connection conn=null;
   
    public AddNew() {
        initComponents();
        conn=(Connection) My_CNX.getConnection();
    }
    
    //Connection con1;
    //PreparedStatement pst;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtspecies = new javax.swing.JTextField();
        txtcommon = new javax.swing.JTextField();
        txtgenus = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtstem = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtleaf = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        lblimage = new javax.swing.JLabel();
        required = new javax.swing.JLabel();
        required2 = new javax.swing.JLabel();
        txtlocation = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtdate = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("New Record");
        setForeground(new java.awt.Color(0, 102, 102));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(java.awt.SystemColor.text);
        jLabel1.setText("New Specimen");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 30));

        jLabel2.setForeground(java.awt.SystemColor.text);
        jLabel2.setText("Common Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        jLabel3.setForeground(java.awt.SystemColor.text);
        jLabel3.setText("Date");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, -1, -1));

        jLabel4.setForeground(java.awt.SystemColor.text);
        jLabel4.setText("Species ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(java.awt.SystemColor.text);
        jLabel5.setText("Picture");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(java.awt.SystemColor.text);
        jLabel6.setText("Characteristics");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/camera.png"))); // NOI18N
        jButton1.setText("Add Photo");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setOpaque(false);
        jButton1.setRolloverEnabled(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 120, 40));

        txtspecies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtspeciesActionPerformed(evt);
            }
        });
        getContentPane().add(txtspecies, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 242, -1));

        txtcommon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcommonActionPerformed(evt);
            }
        });
        getContentPane().add(txtcommon, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 242, -1));
        getContentPane().add(txtgenus, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 242, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setForeground(java.awt.SystemColor.text);
        jLabel7.setText("Stem");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setForeground(java.awt.SystemColor.text);
        jLabel8.setText("Leaf ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/addphoto.png"))); // NOI18N
        jButton2.setText("Upload Speciment");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, -1, -1));

        txtstem.setColumns(20);
        txtstem.setLineWrap(true);
        txtstem.setRows(5);
        jScrollPane1.setViewportView(txtstem);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 318, -1));

        txtleaf.setColumns(20);
        txtleaf.setLineWrap(true);
        txtleaf.setRows(5);
        jScrollPane2.setViewportView(txtleaf);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 318, -1));

        jButton3.setText("Back");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 100, 50));

        lblimage.setBackground(new java.awt.Color(255, 255, 255));
        lblimage.setForeground(new java.awt.Color(255, 255, 255));
        lblimage.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        lblimage.setOpaque(true);
        getContentPane().add(lblimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 170, 179));

        required.setBackground(new java.awt.Color(255, 0, 0));
        required.setForeground(new java.awt.Color(204, 0, 0));
        required.setText("*");
        required.setToolTipText("");
        getContentPane().add(required, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 36, -1));

        required2.setBackground(new java.awt.Color(255, 0, 0));
        required2.setForeground(new java.awt.Color(204, 0, 0));
        required2.setText("*");
        required2.setToolTipText("");
        getContentPane().add(required2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 36, -1));

        txtlocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlocationActionPerformed(evt);
            }
        });
        getContentPane().add(txtlocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 170, 30));

        jLabel9.setForeground(java.awt.SystemColor.text);
        jLabel9.setText("Genus ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        jLabel11.setForeground(java.awt.SystemColor.text);
        jLabel11.setText("Location");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, -1, -1));

        txtdate.setDateFormatString("y-MM-d");
        getContentPane().add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 170, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/background.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtspeciesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtspeciesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtspeciesActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        MainMenu rgf = new MainMenu();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose(); 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String species = txtspecies.getText();
        String genus = txtgenus.getText();
        String common = txtcommon.getText();
        String stem = txtstem.getText();
        String leaf = txtleaf.getText();
        String location = txtlocation.getText();
        String date = ((JTextField)txtdate.getDateEditor().getUiComponent()).getText();

             // check if the data are empty
        if(verifyFields())
        {
        	//check if the common_name already exists
            if(!checkName(genus, species))
                {
                PreparedStatement ps;
                ResultSet rs;
                String registerSpecimenQuery = "INSERT INTO `palm`(`common_name`, `species`, `genus`, `c_stem`, `c_leaf`,`photo`,`location`,`date`) VALUES (?,?,?,?,?,?,?,?)";
            
                try {
                
                    ps = My_CNX.getConnection().prepareStatement(registerSpecimenQuery);
                    ps.setString(1, common);
                    ps.setString(2, species);
                    ps.setString(3, genus);
                    ps.setString(4, stem);
                    ps.setString(5, leaf);
                    ps.setBytes(6, pimage);
                    ps.setString(7, location);
                    ps.setString(8, date);
                    
                
                        if(ps.executeUpdate() != 0){
                            JOptionPane.showMessageDialog(null, "Your Specimen Has Been Added!");
                            AddNew add = new AddNew();
                            add.setVisible(true);
                            add.pack();
                            add.setLocationRelativeTo(null);
                            add.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                            this.dispose();
                        }else{
                            JOptionPane.showMessageDialog(null, "Error: Check Your Information");
                        }
                
                    }
            
                 catch (SQLException ex) {
                    Logger.getLogger(AddNew.class.getName()).log(Level.SEVERE, null, ex);
                }
           }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser fchoser=new JFileChooser();
        fchoser.showOpenDialog(null);
        File f=fchoser.getSelectedFile();
        fname=f.getAbsolutePath();
        ImageIcon micon=new ImageIcon(fname);        
        try {
            File image=new File(fname);
            FileInputStream fis=new FileInputStream(image);
            ByteArrayOutputStream baos=new ByteArrayOutputStream();
            byte[] buf=new byte[1024];
            for(int readnum; (readnum=fis.read(buf)) !=-1;)
            {            
                baos.write(buf,0,readnum);                
            }
            pimage=baos.toByteArray();
            lblimage.setIcon(resizeImage(fname, buf));
        } catch (Exception e) {
        }   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtcommonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcommonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcommonActionPerformed

    private void txtlocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlocationActionPerformed

    // This code use to resize image to fit lable
public ImageIcon resizeImage(String imagePath, byte[] pic){
          
        ImageIcon myImage=null;
        if(imagePath !=null)
        {
        myImage=new ImageIcon(imagePath);
        
        }else{
         myImage=new ImageIcon(pic);
        }
                
        Image img=myImage.getImage();
        Image img2=img.getScaledInstance(lblimage.getHeight(),    lblimage.getWidth(),  Image.SCALE_SMOOTH);
        ImageIcon image=new ImageIcon(img2);
        return image;
}
    public boolean verifyFields()
    {
        String species = txtspecies.getText();
        String genus = txtgenus.getText();
        
        // check empty fields
        if(species.trim().equals("") || genus.trim().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Required Fields * Are Empty","Empty Fields",2);
            return false;
        }
        // if everything is ok
        else{
            return true;
        }
    }        
        
    public boolean checkName(String genus, String species){
        
        PreparedStatement st;
        ResultSet rs;
        boolean name_exist = false;
        
        String query = "SELECT * FROM `palm` WHERE `genus` = ? AND `species` = ?";
        
        try {
            
            st = My_CNX.getConnection().prepareStatement(query);
            st.setString(1, genus);
            st.setString(2, species);
            rs = st.executeQuery();
        
            if(rs.next())
            {
                name_exist = true;
                JOptionPane.showMessageDialog(null, "This Plant Already Exist in the Database", "Failed to Add...", 2);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(AddNew.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return name_exist;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNew().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblimage;
    private javax.swing.JLabel required;
    private javax.swing.JLabel required2;
    private javax.swing.JTextField txtcommon;
    private com.toedter.calendar.JDateChooser txtdate;
    private javax.swing.JTextField txtgenus;
    private javax.swing.JTextArea txtleaf;
    private javax.swing.JTextField txtlocation;
    private javax.swing.JTextField txtspecies;
    private javax.swing.JTextArea txtstem;
    // End of variables declaration//GEN-END:variables
}
